/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PingRouteImport } from './routes/ping';
import { Route as HealthRouteImport } from './routes/health';
import { Route as ProtectedRouteImport } from './routes/_protected';
import { Route as AuthRouteImport } from './routes/_auth';
import { Route as IndexRouteImport } from './routes/index';
import { Route as VerifyEmailChangeEmailTokenRouteImport } from './routes/verify-email-change.$emailToken';
import { Route as ProtectedWorkspacesRouteImport } from './routes/_protected/workspaces';
import { Route as ProtectedUsersRouteImport } from './routes/_protected/users';
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard';
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify';
import { Route as AuthSignupRouteImport } from './routes/_auth/signup';
import { Route as AuthSigninRouteImport } from './routes/_auth/signin';
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password';
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password';
import { Route as ProtectedWorkspacesIndexRouteImport } from './routes/_protected/workspaces/index';
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected/users/index';
import { Route as ApiTestEmailsRouteImport } from './routes/api/test/emails';
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$';
import { Route as ProtectedWorkspacesWorkspaceIdRouteImport } from './routes/_protected/workspaces/$workspaceId';
import { Route as ProtectedUsersUserIdRouteImport } from './routes/_protected/users/$userId';
import { Route as ProtectedAccountAccountRouteImport } from './routes/_protected/_account/account';

const PingRoute = PingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => rootRouteImport,
} as any);
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const VerifyEmailChangeEmailTokenRoute =
  VerifyEmailChangeEmailTokenRouteImport.update({
    id: '/verify-email-change/$emailToken',
    path: '/verify-email-change/$emailToken',
    getParentRoute: () => rootRouteImport,
  } as any);
const ProtectedWorkspacesRoute = ProtectedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedUsersRoute = ProtectedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any);
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any);
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any);
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any);
const ProtectedWorkspacesIndexRoute =
  ProtectedWorkspacesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWorkspacesRoute,
  } as any);
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedUsersRoute,
} as any);
const ApiTestEmailsRoute = ApiTestEmailsRouteImport.update({
  id: '/api/test/emails',
  path: '/api/test/emails',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedWorkspacesWorkspaceIdRoute =
  ProtectedWorkspacesWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => ProtectedWorkspacesRoute,
  } as any);
const ProtectedUsersUserIdRoute = ProtectedUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ProtectedUsersRoute,
} as any);
const ProtectedAccountAccountRoute = ProtectedAccountAccountRouteImport.update({
  id: '/_account/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/health': typeof HealthRoute;
  '/ping': typeof PingRoute;
  '/forgot-password': typeof AuthForgotPasswordRoute;
  '/reset-password': typeof AuthResetPasswordRoute;
  '/signin': typeof AuthSigninRoute;
  '/signup': typeof AuthSignupRoute;
  '/verify': typeof AuthVerifyRoute;
  '/dashboard': typeof ProtectedDashboardRoute;
  '/users': typeof ProtectedUsersRouteWithChildren;
  '/workspaces': typeof ProtectedWorkspacesRouteWithChildren;
  '/verify-email-change/$emailToken': typeof VerifyEmailChangeEmailTokenRoute;
  '/account': typeof ProtectedAccountAccountRoute;
  '/users/$userId': typeof ProtectedUsersUserIdRoute;
  '/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/test/emails': typeof ApiTestEmailsRoute;
  '/users/': typeof ProtectedUsersIndexRoute;
  '/workspaces/': typeof ProtectedWorkspacesIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/health': typeof HealthRoute;
  '/ping': typeof PingRoute;
  '/forgot-password': typeof AuthForgotPasswordRoute;
  '/reset-password': typeof AuthResetPasswordRoute;
  '/signin': typeof AuthSigninRoute;
  '/signup': typeof AuthSignupRoute;
  '/verify': typeof AuthVerifyRoute;
  '/dashboard': typeof ProtectedDashboardRoute;
  '/verify-email-change/$emailToken': typeof VerifyEmailChangeEmailTokenRoute;
  '/account': typeof ProtectedAccountAccountRoute;
  '/users/$userId': typeof ProtectedUsersUserIdRoute;
  '/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/test/emails': typeof ApiTestEmailsRoute;
  '/users': typeof ProtectedUsersIndexRoute;
  '/workspaces': typeof ProtectedWorkspacesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_auth': typeof AuthRouteWithChildren;
  '/_protected': typeof ProtectedRouteWithChildren;
  '/health': typeof HealthRoute;
  '/ping': typeof PingRoute;
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute;
  '/_auth/reset-password': typeof AuthResetPasswordRoute;
  '/_auth/signin': typeof AuthSigninRoute;
  '/_auth/signup': typeof AuthSignupRoute;
  '/_auth/verify': typeof AuthVerifyRoute;
  '/_protected/dashboard': typeof ProtectedDashboardRoute;
  '/_protected/users': typeof ProtectedUsersRouteWithChildren;
  '/_protected/workspaces': typeof ProtectedWorkspacesRouteWithChildren;
  '/verify-email-change/$emailToken': typeof VerifyEmailChangeEmailTokenRoute;
  '/_protected/_account/account': typeof ProtectedAccountAccountRoute;
  '/_protected/users/$userId': typeof ProtectedUsersUserIdRoute;
  '/_protected/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/test/emails': typeof ApiTestEmailsRoute;
  '/_protected/users/': typeof ProtectedUsersIndexRoute;
  '/_protected/workspaces/': typeof ProtectedWorkspacesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/health'
    | '/ping'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/dashboard'
    | '/users'
    | '/workspaces'
    | '/verify-email-change/$emailToken'
    | '/account'
    | '/users/$userId'
    | '/workspaces/$workspaceId'
    | '/api/auth/$'
    | '/api/test/emails'
    | '/users/'
    | '/workspaces/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/health'
    | '/ping'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/dashboard'
    | '/verify-email-change/$emailToken'
    | '/account'
    | '/users/$userId'
    | '/workspaces/$workspaceId'
    | '/api/auth/$'
    | '/api/test/emails'
    | '/users'
    | '/workspaces';
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/health'
    | '/ping'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_auth/verify'
    | '/_protected/dashboard'
    | '/_protected/users'
    | '/_protected/workspaces'
    | '/verify-email-change/$emailToken'
    | '/_protected/_account/account'
    | '/_protected/users/$userId'
    | '/_protected/workspaces/$workspaceId'
    | '/api/auth/$'
    | '/api/test/emails'
    | '/_protected/users/'
    | '/_protected/workspaces/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  ProtectedRoute: typeof ProtectedRouteWithChildren;
  HealthRoute: typeof HealthRoute;
  PingRoute: typeof PingRoute;
  VerifyEmailChangeEmailTokenRoute: typeof VerifyEmailChangeEmailTokenRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiTestEmailsRoute: typeof ApiTestEmailsRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ping': {
      id: '/ping';
      path: '/ping';
      fullPath: '/ping';
      preLoaderRoute: typeof PingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/health': {
      id: '/health';
      path: '/health';
      fullPath: '/health';
      preLoaderRoute: typeof HealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected': {
      id: '/_protected';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/verify-email-change/$emailToken': {
      id: '/verify-email-change/$emailToken';
      path: '/verify-email-change/$emailToken';
      fullPath: '/verify-email-change/$emailToken';
      preLoaderRoute: typeof VerifyEmailChangeEmailTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected/workspaces': {
      id: '/_protected/workspaces';
      path: '/workspaces';
      fullPath: '/workspaces';
      preLoaderRoute: typeof ProtectedWorkspacesRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/users': {
      id: '/_protected/users';
      path: '/users';
      fullPath: '/users';
      preLoaderRoute: typeof ProtectedUsersRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/dashboard': {
      id: '/_protected/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof ProtectedDashboardRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_auth/verify': {
      id: '/_auth/verify';
      path: '/verify';
      fullPath: '/verify';
      preLoaderRoute: typeof AuthVerifyRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/signup': {
      id: '/_auth/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof AuthSignupRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/signin': {
      id: '/_auth/signin';
      path: '/signin';
      fullPath: '/signin';
      preLoaderRoute: typeof AuthSigninRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/reset-password': {
      id: '/_auth/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof AuthResetPasswordRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_protected/workspaces/': {
      id: '/_protected/workspaces/';
      path: '/';
      fullPath: '/workspaces/';
      preLoaderRoute: typeof ProtectedWorkspacesIndexRouteImport;
      parentRoute: typeof ProtectedWorkspacesRoute;
    };
    '/_protected/users/': {
      id: '/_protected/users/';
      path: '/';
      fullPath: '/users/';
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport;
      parentRoute: typeof ProtectedUsersRoute;
    };
    '/api/test/emails': {
      id: '/api/test/emails';
      path: '/api/test/emails';
      fullPath: '/api/test/emails';
      preLoaderRoute: typeof ApiTestEmailsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/auth/$': {
      id: '/api/auth/$';
      path: '/api/auth/$';
      fullPath: '/api/auth/$';
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected/workspaces/$workspaceId': {
      id: '/_protected/workspaces/$workspaceId';
      path: '/$workspaceId';
      fullPath: '/workspaces/$workspaceId';
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdRouteImport;
      parentRoute: typeof ProtectedWorkspacesRoute;
    };
    '/_protected/users/$userId': {
      id: '/_protected/users/$userId';
      path: '/$userId';
      fullPath: '/users/$userId';
      preLoaderRoute: typeof ProtectedUsersUserIdRouteImport;
      parentRoute: typeof ProtectedUsersRoute;
    };
    '/_protected/_account/account': {
      id: '/_protected/_account/account';
      path: '/account';
      fullPath: '/account';
      preLoaderRoute: typeof ProtectedAccountAccountRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  AuthSigninRoute: typeof AuthSigninRoute;
  AuthSignupRoute: typeof AuthSignupRoute;
  AuthVerifyRoute: typeof AuthVerifyRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface ProtectedUsersRouteChildren {
  ProtectedUsersUserIdRoute: typeof ProtectedUsersUserIdRoute;
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute;
}

const ProtectedUsersRouteChildren: ProtectedUsersRouteChildren = {
  ProtectedUsersUserIdRoute: ProtectedUsersUserIdRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
};

const ProtectedUsersRouteWithChildren = ProtectedUsersRoute._addFileChildren(
  ProtectedUsersRouteChildren,
);

interface ProtectedWorkspacesRouteChildren {
  ProtectedWorkspacesWorkspaceIdRoute: typeof ProtectedWorkspacesWorkspaceIdRoute;
  ProtectedWorkspacesIndexRoute: typeof ProtectedWorkspacesIndexRoute;
}

const ProtectedWorkspacesRouteChildren: ProtectedWorkspacesRouteChildren = {
  ProtectedWorkspacesWorkspaceIdRoute: ProtectedWorkspacesWorkspaceIdRoute,
  ProtectedWorkspacesIndexRoute: ProtectedWorkspacesIndexRoute,
};

const ProtectedWorkspacesRouteWithChildren =
  ProtectedWorkspacesRoute._addFileChildren(ProtectedWorkspacesRouteChildren);

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute;
  ProtectedUsersRoute: typeof ProtectedUsersRouteWithChildren;
  ProtectedWorkspacesRoute: typeof ProtectedWorkspacesRouteWithChildren;
  ProtectedAccountAccountRoute: typeof ProtectedAccountAccountRoute;
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedUsersRoute: ProtectedUsersRouteWithChildren,
  ProtectedWorkspacesRoute: ProtectedWorkspacesRouteWithChildren,
  ProtectedAccountAccountRoute: ProtectedAccountAccountRoute,
};

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  HealthRoute: HealthRoute,
  PingRoute: PingRoute,
  VerifyEmailChangeEmailTokenRoute: VerifyEmailChangeEmailTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTestEmailsRoute: ApiTestEmailsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { startInstance } from './start.ts';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
