/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PingRouteImport } from './routes/ping';
import { Route as HealthRouteImport } from './routes/health';
import { Route as AcceptInviteRouteImport } from './routes/accept-invite';
import { Route as ProtectedRouteImport } from './routes/_protected';
import { Route as AuthRouteImport } from './routes/_auth';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AdminIndexRouteImport } from './routes/admin/index';
import { Route as VerifyEmailChangeEmailTokenRouteImport } from './routes/verify-email-change.$emailToken';
import { Route as ApiHelloRouteImport } from './routes/api/hello';
import { Route as AdminAccessDeniedRouteImport } from './routes/admin/access-denied';
import { Route as AdminProtectedRouteImport } from './routes/admin/_protected';
import { Route as ProtectedWsRouteImport } from './routes/_protected/ws';
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify';
import { Route as AuthSignupRouteImport } from './routes/_auth/signup';
import { Route as AuthSigninRouteImport } from './routes/_auth/signin';
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password';
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password';
import { Route as ProtectedWsIndexRouteImport } from './routes/_protected/ws/index';
import { Route as ApiTestEmailsRouteImport } from './routes/api/test/emails';
import { Route as ApiMessagingHelloRouteImport } from './routes/api/messaging/hello';
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$';
import { Route as AdminProtectedWorkspacesRouteImport } from './routes/admin/_protected/workspaces';
import { Route as AdminProtectedUsersRouteImport } from './routes/admin/_protected/users';
import { Route as AdminProtectedDashboardRouteImport } from './routes/admin/_protected/dashboard';
import { Route as ProtectedWsWorkspaceIdRouteImport } from './routes/_protected/ws/$workspaceId';
import { Route as ProtectedAccountNotificationsRouteImport } from './routes/_protected/_account/notifications';
import { Route as ProtectedAccountBillingRouteImport } from './routes/_protected/_account/billing';
import { Route as ProtectedAccountAccountRouteImport } from './routes/_protected/_account/account';
import { Route as AdminProtectedWorkspacesIndexRouteImport } from './routes/admin/_protected/workspaces/index';
import { Route as AdminProtectedUsersIndexRouteImport } from './routes/admin/_protected/users/index';
import { Route as AdminProtectedWorkspacesWorkspaceIdRouteImport } from './routes/admin/_protected/workspaces/$workspaceId';
import { Route as AdminProtectedUsersUserIdRouteImport } from './routes/admin/_protected/users/$userId';
import { Route as ProtectedWsWorkspaceIdSettingsRouteImport } from './routes/_protected/ws/$workspaceId/settings';
import { Route as ProtectedWsWorkspaceIdProjectsRouteImport } from './routes/_protected/ws/$workspaceId/projects';
import { Route as ProtectedWsWorkspaceIdOverviewRouteImport } from './routes/_protected/ws/$workspaceId/overview';
import { Route as ProtectedWsWorkspaceIdMembersRouteImport } from './routes/_protected/ws/$workspaceId/members';
import { Route as ProtectedWsWorkspaceIdIntegrationsRouteImport } from './routes/_protected/ws/$workspaceId/integrations';
import { Route as ProtectedWsWorkspaceIdBillingRouteImport } from './routes/_protected/ws/$workspaceId/billing';

const PingRoute = PingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => rootRouteImport,
} as any);
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any);
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any);
const VerifyEmailChangeEmailTokenRoute =
  VerifyEmailChangeEmailTokenRouteImport.update({
    id: '/verify-email-change/$emailToken',
    path: '/verify-email-change/$emailToken',
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/api/hello',
  path: '/api/hello',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminAccessDeniedRoute = AdminAccessDeniedRouteImport.update({
  id: '/admin/access-denied',
  path: '/admin/access-denied',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminProtectedRoute = AdminProtectedRouteImport.update({
  id: '/admin/_protected',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedWsRoute = ProtectedWsRouteImport.update({
  id: '/ws',
  path: '/ws',
  getParentRoute: () => ProtectedRoute,
} as any);
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any);
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any);
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any);
const ProtectedWsIndexRoute = ProtectedWsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedWsRoute,
} as any);
const ApiTestEmailsRoute = ApiTestEmailsRouteImport.update({
  id: '/api/test/emails',
  path: '/api/test/emails',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiMessagingHelloRoute = ApiMessagingHelloRouteImport.update({
  id: '/api/messaging/hello',
  path: '/api/messaging/hello',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminProtectedWorkspacesRoute =
  AdminProtectedWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AdminProtectedRoute,
  } as any);
const AdminProtectedUsersRoute = AdminProtectedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminProtectedRoute,
} as any);
const AdminProtectedDashboardRoute = AdminProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminProtectedRoute,
} as any);
const ProtectedWsWorkspaceIdRoute = ProtectedWsWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => ProtectedWsRoute,
} as any);
const ProtectedAccountNotificationsRoute =
  ProtectedAccountNotificationsRouteImport.update({
    id: '/_account/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedRoute,
  } as any);
const ProtectedAccountBillingRoute = ProtectedAccountBillingRouteImport.update({
  id: '/_account/billing',
  path: '/billing',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedAccountAccountRoute = ProtectedAccountAccountRouteImport.update({
  id: '/_account/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any);
const AdminProtectedWorkspacesIndexRoute =
  AdminProtectedWorkspacesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminProtectedWorkspacesRoute,
  } as any);
const AdminProtectedUsersIndexRoute =
  AdminProtectedUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminProtectedUsersRoute,
  } as any);
const AdminProtectedWorkspacesWorkspaceIdRoute =
  AdminProtectedWorkspacesWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => AdminProtectedWorkspacesRoute,
  } as any);
const AdminProtectedUsersUserIdRoute =
  AdminProtectedUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AdminProtectedUsersRoute,
  } as any);
const ProtectedWsWorkspaceIdSettingsRoute =
  ProtectedWsWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedWsWorkspaceIdRoute,
  } as any);
const ProtectedWsWorkspaceIdProjectsRoute =
  ProtectedWsWorkspaceIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => ProtectedWsWorkspaceIdRoute,
  } as any);
const ProtectedWsWorkspaceIdOverviewRoute =
  ProtectedWsWorkspaceIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProtectedWsWorkspaceIdRoute,
  } as any);
const ProtectedWsWorkspaceIdMembersRoute =
  ProtectedWsWorkspaceIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProtectedWsWorkspaceIdRoute,
  } as any);
const ProtectedWsWorkspaceIdIntegrationsRoute =
  ProtectedWsWorkspaceIdIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => ProtectedWsWorkspaceIdRoute,
  } as any);
const ProtectedWsWorkspaceIdBillingRoute =
  ProtectedWsWorkspaceIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ProtectedWsWorkspaceIdRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/accept-invite': typeof AcceptInviteRoute;
  '/health': typeof HealthRoute;
  '/ping': typeof PingRoute;
  '/forgot-password': typeof AuthForgotPasswordRoute;
  '/reset-password': typeof AuthResetPasswordRoute;
  '/signin': typeof AuthSigninRoute;
  '/signup': typeof AuthSignupRoute;
  '/verify': typeof AuthVerifyRoute;
  '/ws': typeof ProtectedWsRouteWithChildren;
  '/admin': typeof AdminProtectedRouteWithChildren;
  '/admin/access-denied': typeof AdminAccessDeniedRoute;
  '/api/hello': typeof ApiHelloRoute;
  '/verify-email-change/$emailToken': typeof VerifyEmailChangeEmailTokenRoute;
  '/admin/': typeof AdminIndexRoute;
  '/account': typeof ProtectedAccountAccountRoute;
  '/billing': typeof ProtectedAccountBillingRoute;
  '/notifications': typeof ProtectedAccountNotificationsRoute;
  '/ws/$workspaceId': typeof ProtectedWsWorkspaceIdRouteWithChildren;
  '/admin/dashboard': typeof AdminProtectedDashboardRoute;
  '/admin/users': typeof AdminProtectedUsersRouteWithChildren;
  '/admin/workspaces': typeof AdminProtectedWorkspacesRouteWithChildren;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/messaging/hello': typeof ApiMessagingHelloRoute;
  '/api/test/emails': typeof ApiTestEmailsRoute;
  '/ws/': typeof ProtectedWsIndexRoute;
  '/ws/$workspaceId/billing': typeof ProtectedWsWorkspaceIdBillingRoute;
  '/ws/$workspaceId/integrations': typeof ProtectedWsWorkspaceIdIntegrationsRoute;
  '/ws/$workspaceId/members': typeof ProtectedWsWorkspaceIdMembersRoute;
  '/ws/$workspaceId/overview': typeof ProtectedWsWorkspaceIdOverviewRoute;
  '/ws/$workspaceId/projects': typeof ProtectedWsWorkspaceIdProjectsRoute;
  '/ws/$workspaceId/settings': typeof ProtectedWsWorkspaceIdSettingsRoute;
  '/admin/users/$userId': typeof AdminProtectedUsersUserIdRoute;
  '/admin/workspaces/$workspaceId': typeof AdminProtectedWorkspacesWorkspaceIdRoute;
  '/admin/users/': typeof AdminProtectedUsersIndexRoute;
  '/admin/workspaces/': typeof AdminProtectedWorkspacesIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/accept-invite': typeof AcceptInviteRoute;
  '/health': typeof HealthRoute;
  '/ping': typeof PingRoute;
  '/forgot-password': typeof AuthForgotPasswordRoute;
  '/reset-password': typeof AuthResetPasswordRoute;
  '/signin': typeof AuthSigninRoute;
  '/signup': typeof AuthSignupRoute;
  '/verify': typeof AuthVerifyRoute;
  '/admin': typeof AdminIndexRoute;
  '/admin/access-denied': typeof AdminAccessDeniedRoute;
  '/api/hello': typeof ApiHelloRoute;
  '/verify-email-change/$emailToken': typeof VerifyEmailChangeEmailTokenRoute;
  '/account': typeof ProtectedAccountAccountRoute;
  '/billing': typeof ProtectedAccountBillingRoute;
  '/notifications': typeof ProtectedAccountNotificationsRoute;
  '/ws/$workspaceId': typeof ProtectedWsWorkspaceIdRouteWithChildren;
  '/admin/dashboard': typeof AdminProtectedDashboardRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/messaging/hello': typeof ApiMessagingHelloRoute;
  '/api/test/emails': typeof ApiTestEmailsRoute;
  '/ws': typeof ProtectedWsIndexRoute;
  '/ws/$workspaceId/billing': typeof ProtectedWsWorkspaceIdBillingRoute;
  '/ws/$workspaceId/integrations': typeof ProtectedWsWorkspaceIdIntegrationsRoute;
  '/ws/$workspaceId/members': typeof ProtectedWsWorkspaceIdMembersRoute;
  '/ws/$workspaceId/overview': typeof ProtectedWsWorkspaceIdOverviewRoute;
  '/ws/$workspaceId/projects': typeof ProtectedWsWorkspaceIdProjectsRoute;
  '/ws/$workspaceId/settings': typeof ProtectedWsWorkspaceIdSettingsRoute;
  '/admin/users/$userId': typeof AdminProtectedUsersUserIdRoute;
  '/admin/workspaces/$workspaceId': typeof AdminProtectedWorkspacesWorkspaceIdRoute;
  '/admin/users': typeof AdminProtectedUsersIndexRoute;
  '/admin/workspaces': typeof AdminProtectedWorkspacesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_auth': typeof AuthRouteWithChildren;
  '/_protected': typeof ProtectedRouteWithChildren;
  '/accept-invite': typeof AcceptInviteRoute;
  '/health': typeof HealthRoute;
  '/ping': typeof PingRoute;
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute;
  '/_auth/reset-password': typeof AuthResetPasswordRoute;
  '/_auth/signin': typeof AuthSigninRoute;
  '/_auth/signup': typeof AuthSignupRoute;
  '/_auth/verify': typeof AuthVerifyRoute;
  '/_protected/ws': typeof ProtectedWsRouteWithChildren;
  '/admin/_protected': typeof AdminProtectedRouteWithChildren;
  '/admin/access-denied': typeof AdminAccessDeniedRoute;
  '/api/hello': typeof ApiHelloRoute;
  '/verify-email-change/$emailToken': typeof VerifyEmailChangeEmailTokenRoute;
  '/admin/': typeof AdminIndexRoute;
  '/_protected/_account/account': typeof ProtectedAccountAccountRoute;
  '/_protected/_account/billing': typeof ProtectedAccountBillingRoute;
  '/_protected/_account/notifications': typeof ProtectedAccountNotificationsRoute;
  '/_protected/ws/$workspaceId': typeof ProtectedWsWorkspaceIdRouteWithChildren;
  '/admin/_protected/dashboard': typeof AdminProtectedDashboardRoute;
  '/admin/_protected/users': typeof AdminProtectedUsersRouteWithChildren;
  '/admin/_protected/workspaces': typeof AdminProtectedWorkspacesRouteWithChildren;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/messaging/hello': typeof ApiMessagingHelloRoute;
  '/api/test/emails': typeof ApiTestEmailsRoute;
  '/_protected/ws/': typeof ProtectedWsIndexRoute;
  '/_protected/ws/$workspaceId/billing': typeof ProtectedWsWorkspaceIdBillingRoute;
  '/_protected/ws/$workspaceId/integrations': typeof ProtectedWsWorkspaceIdIntegrationsRoute;
  '/_protected/ws/$workspaceId/members': typeof ProtectedWsWorkspaceIdMembersRoute;
  '/_protected/ws/$workspaceId/overview': typeof ProtectedWsWorkspaceIdOverviewRoute;
  '/_protected/ws/$workspaceId/projects': typeof ProtectedWsWorkspaceIdProjectsRoute;
  '/_protected/ws/$workspaceId/settings': typeof ProtectedWsWorkspaceIdSettingsRoute;
  '/admin/_protected/users/$userId': typeof AdminProtectedUsersUserIdRoute;
  '/admin/_protected/workspaces/$workspaceId': typeof AdminProtectedWorkspacesWorkspaceIdRoute;
  '/admin/_protected/users/': typeof AdminProtectedUsersIndexRoute;
  '/admin/_protected/workspaces/': typeof AdminProtectedWorkspacesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/health'
    | '/ping'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/ws'
    | '/admin'
    | '/admin/access-denied'
    | '/api/hello'
    | '/verify-email-change/$emailToken'
    | '/admin/'
    | '/account'
    | '/billing'
    | '/notifications'
    | '/ws/$workspaceId'
    | '/admin/dashboard'
    | '/admin/users'
    | '/admin/workspaces'
    | '/api/auth/$'
    | '/api/messaging/hello'
    | '/api/test/emails'
    | '/ws/'
    | '/ws/$workspaceId/billing'
    | '/ws/$workspaceId/integrations'
    | '/ws/$workspaceId/members'
    | '/ws/$workspaceId/overview'
    | '/ws/$workspaceId/projects'
    | '/ws/$workspaceId/settings'
    | '/admin/users/$userId'
    | '/admin/workspaces/$workspaceId'
    | '/admin/users/'
    | '/admin/workspaces/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/accept-invite'
    | '/health'
    | '/ping'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/admin'
    | '/admin/access-denied'
    | '/api/hello'
    | '/verify-email-change/$emailToken'
    | '/account'
    | '/billing'
    | '/notifications'
    | '/ws/$workspaceId'
    | '/admin/dashboard'
    | '/api/auth/$'
    | '/api/messaging/hello'
    | '/api/test/emails'
    | '/ws'
    | '/ws/$workspaceId/billing'
    | '/ws/$workspaceId/integrations'
    | '/ws/$workspaceId/members'
    | '/ws/$workspaceId/overview'
    | '/ws/$workspaceId/projects'
    | '/ws/$workspaceId/settings'
    | '/admin/users/$userId'
    | '/admin/workspaces/$workspaceId'
    | '/admin/users'
    | '/admin/workspaces';
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/accept-invite'
    | '/health'
    | '/ping'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_auth/verify'
    | '/_protected/ws'
    | '/admin/_protected'
    | '/admin/access-denied'
    | '/api/hello'
    | '/verify-email-change/$emailToken'
    | '/admin/'
    | '/_protected/_account/account'
    | '/_protected/_account/billing'
    | '/_protected/_account/notifications'
    | '/_protected/ws/$workspaceId'
    | '/admin/_protected/dashboard'
    | '/admin/_protected/users'
    | '/admin/_protected/workspaces'
    | '/api/auth/$'
    | '/api/messaging/hello'
    | '/api/test/emails'
    | '/_protected/ws/'
    | '/_protected/ws/$workspaceId/billing'
    | '/_protected/ws/$workspaceId/integrations'
    | '/_protected/ws/$workspaceId/members'
    | '/_protected/ws/$workspaceId/overview'
    | '/_protected/ws/$workspaceId/projects'
    | '/_protected/ws/$workspaceId/settings'
    | '/admin/_protected/users/$userId'
    | '/admin/_protected/workspaces/$workspaceId'
    | '/admin/_protected/users/'
    | '/admin/_protected/workspaces/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  ProtectedRoute: typeof ProtectedRouteWithChildren;
  AcceptInviteRoute: typeof AcceptInviteRoute;
  HealthRoute: typeof HealthRoute;
  PingRoute: typeof PingRoute;
  AdminProtectedRoute: typeof AdminProtectedRouteWithChildren;
  AdminAccessDeniedRoute: typeof AdminAccessDeniedRoute;
  ApiHelloRoute: typeof ApiHelloRoute;
  VerifyEmailChangeEmailTokenRoute: typeof VerifyEmailChangeEmailTokenRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiMessagingHelloRoute: typeof ApiMessagingHelloRoute;
  ApiTestEmailsRoute: typeof ApiTestEmailsRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ping': {
      id: '/ping';
      path: '/ping';
      fullPath: '/ping';
      preLoaderRoute: typeof PingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/health': {
      id: '/health';
      path: '/health';
      fullPath: '/health';
      preLoaderRoute: typeof HealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/accept-invite': {
      id: '/accept-invite';
      path: '/accept-invite';
      fullPath: '/accept-invite';
      preLoaderRoute: typeof AcceptInviteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected': {
      id: '/_protected';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin/': {
      id: '/admin/';
      path: '/admin';
      fullPath: '/admin/';
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/verify-email-change/$emailToken': {
      id: '/verify-email-change/$emailToken';
      path: '/verify-email-change/$emailToken';
      fullPath: '/verify-email-change/$emailToken';
      preLoaderRoute: typeof VerifyEmailChangeEmailTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/hello': {
      id: '/api/hello';
      path: '/api/hello';
      fullPath: '/api/hello';
      preLoaderRoute: typeof ApiHelloRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin/access-denied': {
      id: '/admin/access-denied';
      path: '/admin/access-denied';
      fullPath: '/admin/access-denied';
      preLoaderRoute: typeof AdminAccessDeniedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin/_protected': {
      id: '/admin/_protected';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected/ws': {
      id: '/_protected/ws';
      path: '/ws';
      fullPath: '/ws';
      preLoaderRoute: typeof ProtectedWsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_auth/verify': {
      id: '/_auth/verify';
      path: '/verify';
      fullPath: '/verify';
      preLoaderRoute: typeof AuthVerifyRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/signup': {
      id: '/_auth/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof AuthSignupRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/signin': {
      id: '/_auth/signin';
      path: '/signin';
      fullPath: '/signin';
      preLoaderRoute: typeof AuthSigninRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/reset-password': {
      id: '/_auth/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof AuthResetPasswordRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_protected/ws/': {
      id: '/_protected/ws/';
      path: '/';
      fullPath: '/ws/';
      preLoaderRoute: typeof ProtectedWsIndexRouteImport;
      parentRoute: typeof ProtectedWsRoute;
    };
    '/api/test/emails': {
      id: '/api/test/emails';
      path: '/api/test/emails';
      fullPath: '/api/test/emails';
      preLoaderRoute: typeof ApiTestEmailsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/messaging/hello': {
      id: '/api/messaging/hello';
      path: '/api/messaging/hello';
      fullPath: '/api/messaging/hello';
      preLoaderRoute: typeof ApiMessagingHelloRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/auth/$': {
      id: '/api/auth/$';
      path: '/api/auth/$';
      fullPath: '/api/auth/$';
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin/_protected/workspaces': {
      id: '/admin/_protected/workspaces';
      path: '/workspaces';
      fullPath: '/admin/workspaces';
      preLoaderRoute: typeof AdminProtectedWorkspacesRouteImport;
      parentRoute: typeof AdminProtectedRoute;
    };
    '/admin/_protected/users': {
      id: '/admin/_protected/users';
      path: '/users';
      fullPath: '/admin/users';
      preLoaderRoute: typeof AdminProtectedUsersRouteImport;
      parentRoute: typeof AdminProtectedRoute;
    };
    '/admin/_protected/dashboard': {
      id: '/admin/_protected/dashboard';
      path: '/dashboard';
      fullPath: '/admin/dashboard';
      preLoaderRoute: typeof AdminProtectedDashboardRouteImport;
      parentRoute: typeof AdminProtectedRoute;
    };
    '/_protected/ws/$workspaceId': {
      id: '/_protected/ws/$workspaceId';
      path: '/$workspaceId';
      fullPath: '/ws/$workspaceId';
      preLoaderRoute: typeof ProtectedWsWorkspaceIdRouteImport;
      parentRoute: typeof ProtectedWsRoute;
    };
    '/_protected/_account/notifications': {
      id: '/_protected/_account/notifications';
      path: '/notifications';
      fullPath: '/notifications';
      preLoaderRoute: typeof ProtectedAccountNotificationsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/_account/billing': {
      id: '/_protected/_account/billing';
      path: '/billing';
      fullPath: '/billing';
      preLoaderRoute: typeof ProtectedAccountBillingRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/_account/account': {
      id: '/_protected/_account/account';
      path: '/account';
      fullPath: '/account';
      preLoaderRoute: typeof ProtectedAccountAccountRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/admin/_protected/workspaces/': {
      id: '/admin/_protected/workspaces/';
      path: '/';
      fullPath: '/admin/workspaces/';
      preLoaderRoute: typeof AdminProtectedWorkspacesIndexRouteImport;
      parentRoute: typeof AdminProtectedWorkspacesRoute;
    };
    '/admin/_protected/users/': {
      id: '/admin/_protected/users/';
      path: '/';
      fullPath: '/admin/users/';
      preLoaderRoute: typeof AdminProtectedUsersIndexRouteImport;
      parentRoute: typeof AdminProtectedUsersRoute;
    };
    '/admin/_protected/workspaces/$workspaceId': {
      id: '/admin/_protected/workspaces/$workspaceId';
      path: '/$workspaceId';
      fullPath: '/admin/workspaces/$workspaceId';
      preLoaderRoute: typeof AdminProtectedWorkspacesWorkspaceIdRouteImport;
      parentRoute: typeof AdminProtectedWorkspacesRoute;
    };
    '/admin/_protected/users/$userId': {
      id: '/admin/_protected/users/$userId';
      path: '/$userId';
      fullPath: '/admin/users/$userId';
      preLoaderRoute: typeof AdminProtectedUsersUserIdRouteImport;
      parentRoute: typeof AdminProtectedUsersRoute;
    };
    '/_protected/ws/$workspaceId/settings': {
      id: '/_protected/ws/$workspaceId/settings';
      path: '/settings';
      fullPath: '/ws/$workspaceId/settings';
      preLoaderRoute: typeof ProtectedWsWorkspaceIdSettingsRouteImport;
      parentRoute: typeof ProtectedWsWorkspaceIdRoute;
    };
    '/_protected/ws/$workspaceId/projects': {
      id: '/_protected/ws/$workspaceId/projects';
      path: '/projects';
      fullPath: '/ws/$workspaceId/projects';
      preLoaderRoute: typeof ProtectedWsWorkspaceIdProjectsRouteImport;
      parentRoute: typeof ProtectedWsWorkspaceIdRoute;
    };
    '/_protected/ws/$workspaceId/overview': {
      id: '/_protected/ws/$workspaceId/overview';
      path: '/overview';
      fullPath: '/ws/$workspaceId/overview';
      preLoaderRoute: typeof ProtectedWsWorkspaceIdOverviewRouteImport;
      parentRoute: typeof ProtectedWsWorkspaceIdRoute;
    };
    '/_protected/ws/$workspaceId/members': {
      id: '/_protected/ws/$workspaceId/members';
      path: '/members';
      fullPath: '/ws/$workspaceId/members';
      preLoaderRoute: typeof ProtectedWsWorkspaceIdMembersRouteImport;
      parentRoute: typeof ProtectedWsWorkspaceIdRoute;
    };
    '/_protected/ws/$workspaceId/integrations': {
      id: '/_protected/ws/$workspaceId/integrations';
      path: '/integrations';
      fullPath: '/ws/$workspaceId/integrations';
      preLoaderRoute: typeof ProtectedWsWorkspaceIdIntegrationsRouteImport;
      parentRoute: typeof ProtectedWsWorkspaceIdRoute;
    };
    '/_protected/ws/$workspaceId/billing': {
      id: '/_protected/ws/$workspaceId/billing';
      path: '/billing';
      fullPath: '/ws/$workspaceId/billing';
      preLoaderRoute: typeof ProtectedWsWorkspaceIdBillingRouteImport;
      parentRoute: typeof ProtectedWsWorkspaceIdRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  AuthSigninRoute: typeof AuthSigninRoute;
  AuthSignupRoute: typeof AuthSignupRoute;
  AuthVerifyRoute: typeof AuthVerifyRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface ProtectedWsWorkspaceIdRouteChildren {
  ProtectedWsWorkspaceIdBillingRoute: typeof ProtectedWsWorkspaceIdBillingRoute;
  ProtectedWsWorkspaceIdIntegrationsRoute: typeof ProtectedWsWorkspaceIdIntegrationsRoute;
  ProtectedWsWorkspaceIdMembersRoute: typeof ProtectedWsWorkspaceIdMembersRoute;
  ProtectedWsWorkspaceIdOverviewRoute: typeof ProtectedWsWorkspaceIdOverviewRoute;
  ProtectedWsWorkspaceIdProjectsRoute: typeof ProtectedWsWorkspaceIdProjectsRoute;
  ProtectedWsWorkspaceIdSettingsRoute: typeof ProtectedWsWorkspaceIdSettingsRoute;
}

const ProtectedWsWorkspaceIdRouteChildren: ProtectedWsWorkspaceIdRouteChildren =
  {
    ProtectedWsWorkspaceIdBillingRoute: ProtectedWsWorkspaceIdBillingRoute,
    ProtectedWsWorkspaceIdIntegrationsRoute:
      ProtectedWsWorkspaceIdIntegrationsRoute,
    ProtectedWsWorkspaceIdMembersRoute: ProtectedWsWorkspaceIdMembersRoute,
    ProtectedWsWorkspaceIdOverviewRoute: ProtectedWsWorkspaceIdOverviewRoute,
    ProtectedWsWorkspaceIdProjectsRoute: ProtectedWsWorkspaceIdProjectsRoute,
    ProtectedWsWorkspaceIdSettingsRoute: ProtectedWsWorkspaceIdSettingsRoute,
  };

const ProtectedWsWorkspaceIdRouteWithChildren =
  ProtectedWsWorkspaceIdRoute._addFileChildren(
    ProtectedWsWorkspaceIdRouteChildren,
  );

interface ProtectedWsRouteChildren {
  ProtectedWsWorkspaceIdRoute: typeof ProtectedWsWorkspaceIdRouteWithChildren;
  ProtectedWsIndexRoute: typeof ProtectedWsIndexRoute;
}

const ProtectedWsRouteChildren: ProtectedWsRouteChildren = {
  ProtectedWsWorkspaceIdRoute: ProtectedWsWorkspaceIdRouteWithChildren,
  ProtectedWsIndexRoute: ProtectedWsIndexRoute,
};

const ProtectedWsRouteWithChildren = ProtectedWsRoute._addFileChildren(
  ProtectedWsRouteChildren,
);

interface ProtectedRouteChildren {
  ProtectedWsRoute: typeof ProtectedWsRouteWithChildren;
  ProtectedAccountAccountRoute: typeof ProtectedAccountAccountRoute;
  ProtectedAccountBillingRoute: typeof ProtectedAccountBillingRoute;
  ProtectedAccountNotificationsRoute: typeof ProtectedAccountNotificationsRoute;
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedWsRoute: ProtectedWsRouteWithChildren,
  ProtectedAccountAccountRoute: ProtectedAccountAccountRoute,
  ProtectedAccountBillingRoute: ProtectedAccountBillingRoute,
  ProtectedAccountNotificationsRoute: ProtectedAccountNotificationsRoute,
};

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
);

interface AdminProtectedUsersRouteChildren {
  AdminProtectedUsersUserIdRoute: typeof AdminProtectedUsersUserIdRoute;
  AdminProtectedUsersIndexRoute: typeof AdminProtectedUsersIndexRoute;
}

const AdminProtectedUsersRouteChildren: AdminProtectedUsersRouteChildren = {
  AdminProtectedUsersUserIdRoute: AdminProtectedUsersUserIdRoute,
  AdminProtectedUsersIndexRoute: AdminProtectedUsersIndexRoute,
};

const AdminProtectedUsersRouteWithChildren =
  AdminProtectedUsersRoute._addFileChildren(AdminProtectedUsersRouteChildren);

interface AdminProtectedWorkspacesRouteChildren {
  AdminProtectedWorkspacesWorkspaceIdRoute: typeof AdminProtectedWorkspacesWorkspaceIdRoute;
  AdminProtectedWorkspacesIndexRoute: typeof AdminProtectedWorkspacesIndexRoute;
}

const AdminProtectedWorkspacesRouteChildren: AdminProtectedWorkspacesRouteChildren =
  {
    AdminProtectedWorkspacesWorkspaceIdRoute:
      AdminProtectedWorkspacesWorkspaceIdRoute,
    AdminProtectedWorkspacesIndexRoute: AdminProtectedWorkspacesIndexRoute,
  };

const AdminProtectedWorkspacesRouteWithChildren =
  AdminProtectedWorkspacesRoute._addFileChildren(
    AdminProtectedWorkspacesRouteChildren,
  );

interface AdminProtectedRouteChildren {
  AdminProtectedDashboardRoute: typeof AdminProtectedDashboardRoute;
  AdminProtectedUsersRoute: typeof AdminProtectedUsersRouteWithChildren;
  AdminProtectedWorkspacesRoute: typeof AdminProtectedWorkspacesRouteWithChildren;
}

const AdminProtectedRouteChildren: AdminProtectedRouteChildren = {
  AdminProtectedDashboardRoute: AdminProtectedDashboardRoute,
  AdminProtectedUsersRoute: AdminProtectedUsersRouteWithChildren,
  AdminProtectedWorkspacesRoute: AdminProtectedWorkspacesRouteWithChildren,
};

const AdminProtectedRouteWithChildren = AdminProtectedRoute._addFileChildren(
  AdminProtectedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  HealthRoute: HealthRoute,
  PingRoute: PingRoute,
  AdminProtectedRoute: AdminProtectedRouteWithChildren,
  AdminAccessDeniedRoute: AdminAccessDeniedRoute,
  ApiHelloRoute: ApiHelloRoute,
  VerifyEmailChangeEmailTokenRoute: VerifyEmailChangeEmailTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMessagingHelloRoute: ApiMessagingHelloRoute,
  ApiTestEmailsRoute: ApiTestEmailsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { startInstance } from './start.ts';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
