/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PingRouteImport } from './routes/ping';
import { Route as HealthRouteImport } from './routes/health';
import { Route as AcceptInviteRouteImport } from './routes/accept-invite';
import { Route as ProtectedRouteImport } from './routes/_protected';
import { Route as AuthRouteImport } from './routes/_auth';
import { Route as IndexRouteImport } from './routes/index';
import { Route as VerifyEmailChangeEmailTokenRouteImport } from './routes/verify-email-change.$emailToken';
import { Route as ProtectedWsRouteImport } from './routes/_protected/ws';
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin';
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify';
import { Route as AuthSignupRouteImport } from './routes/_auth/signup';
import { Route as AuthSigninRouteImport } from './routes/_auth/signin';
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password';
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password';
import { Route as ProtectedWsIndexRouteImport } from './routes/_protected/ws/index';
import { Route as ApiTestEmailsRouteImport } from './routes/api/test/emails';
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$';
import { Route as ProtectedWsWorkspaceIdRouteImport } from './routes/_protected/ws/$workspaceId';
import { Route as ProtectedAdminUserRouteImport } from './routes/_protected/admin/user';
import { Route as ProtectedAdminDashboardRouteImport } from './routes/_protected/admin/dashboard';
import { Route as ProtectedAccountNotificationsRouteImport } from './routes/_protected/_account/notifications';
import { Route as ProtectedAccountBillingRouteImport } from './routes/_protected/_account/billing';
import { Route as ProtectedAccountAccountRouteImport } from './routes/_protected/_account/account';
import { Route as ProtectedAdminUserIndexRouteImport } from './routes/_protected/admin/user/index';
import { Route as ProtectedWsWorkspaceIdSettingsRouteImport } from './routes/_protected/ws/$workspaceId/settings';
import { Route as ProtectedWsWorkspaceIdProjectsRouteImport } from './routes/_protected/ws/$workspaceId/projects';
import { Route as ProtectedWsWorkspaceIdOverviewRouteImport } from './routes/_protected/ws/$workspaceId/overview';
import { Route as ProtectedWsWorkspaceIdMembersRouteImport } from './routes/_protected/ws/$workspaceId/members';
import { Route as ProtectedWsWorkspaceIdBillingRouteImport } from './routes/_protected/ws/$workspaceId/billing';
import { Route as ProtectedAdminUserUserIdRouteImport } from './routes/_protected/admin/user/$userId';

const PingRoute = PingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => rootRouteImport,
} as any);
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any);
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const VerifyEmailChangeEmailTokenRoute =
  VerifyEmailChangeEmailTokenRouteImport.update({
    id: '/verify-email-change/$emailToken',
    path: '/verify-email-change/$emailToken',
    getParentRoute: () => rootRouteImport,
  } as any);
const ProtectedWsRoute = ProtectedWsRouteImport.update({
  id: '/ws',
  path: '/ws',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any);
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any);
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any);
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any);
const ProtectedWsIndexRoute = ProtectedWsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedWsRoute,
} as any);
const ApiTestEmailsRoute = ApiTestEmailsRouteImport.update({
  id: '/api/test/emails',
  path: '/api/test/emails',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedWsWorkspaceIdRoute = ProtectedWsWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => ProtectedWsRoute,
} as any);
const ProtectedAdminUserRoute = ProtectedAdminUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => ProtectedAdminRoute,
} as any);
const ProtectedAdminDashboardRoute = ProtectedAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedAdminRoute,
} as any);
const ProtectedAccountNotificationsRoute =
  ProtectedAccountNotificationsRouteImport.update({
    id: '/_account/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedRoute,
  } as any);
const ProtectedAccountBillingRoute = ProtectedAccountBillingRouteImport.update({
  id: '/_account/billing',
  path: '/billing',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedAccountAccountRoute = ProtectedAccountAccountRouteImport.update({
  id: '/_account/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedAdminUserIndexRoute = ProtectedAdminUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminUserRoute,
} as any);
const ProtectedWsWorkspaceIdSettingsRoute =
  ProtectedWsWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedWsWorkspaceIdRoute,
  } as any);
const ProtectedWsWorkspaceIdProjectsRoute =
  ProtectedWsWorkspaceIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => ProtectedWsWorkspaceIdRoute,
  } as any);
const ProtectedWsWorkspaceIdOverviewRoute =
  ProtectedWsWorkspaceIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProtectedWsWorkspaceIdRoute,
  } as any);
const ProtectedWsWorkspaceIdMembersRoute =
  ProtectedWsWorkspaceIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProtectedWsWorkspaceIdRoute,
  } as any);
const ProtectedWsWorkspaceIdBillingRoute =
  ProtectedWsWorkspaceIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ProtectedWsWorkspaceIdRoute,
  } as any);
const ProtectedAdminUserUserIdRoute =
  ProtectedAdminUserUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => ProtectedAdminUserRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/accept-invite': typeof AcceptInviteRoute;
  '/health': typeof HealthRoute;
  '/ping': typeof PingRoute;
  '/forgot-password': typeof AuthForgotPasswordRoute;
  '/reset-password': typeof AuthResetPasswordRoute;
  '/signin': typeof AuthSigninRoute;
  '/signup': typeof AuthSignupRoute;
  '/verify': typeof AuthVerifyRoute;
  '/admin': typeof ProtectedAdminRouteWithChildren;
  '/ws': typeof ProtectedWsRouteWithChildren;
  '/verify-email-change/$emailToken': typeof VerifyEmailChangeEmailTokenRoute;
  '/account': typeof ProtectedAccountAccountRoute;
  '/billing': typeof ProtectedAccountBillingRoute;
  '/notifications': typeof ProtectedAccountNotificationsRoute;
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute;
  '/admin/user': typeof ProtectedAdminUserRouteWithChildren;
  '/ws/$workspaceId': typeof ProtectedWsWorkspaceIdRouteWithChildren;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/test/emails': typeof ApiTestEmailsRoute;
  '/ws/': typeof ProtectedWsIndexRoute;
  '/admin/user/$userId': typeof ProtectedAdminUserUserIdRoute;
  '/ws/$workspaceId/billing': typeof ProtectedWsWorkspaceIdBillingRoute;
  '/ws/$workspaceId/members': typeof ProtectedWsWorkspaceIdMembersRoute;
  '/ws/$workspaceId/overview': typeof ProtectedWsWorkspaceIdOverviewRoute;
  '/ws/$workspaceId/projects': typeof ProtectedWsWorkspaceIdProjectsRoute;
  '/ws/$workspaceId/settings': typeof ProtectedWsWorkspaceIdSettingsRoute;
  '/admin/user/': typeof ProtectedAdminUserIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/accept-invite': typeof AcceptInviteRoute;
  '/health': typeof HealthRoute;
  '/ping': typeof PingRoute;
  '/forgot-password': typeof AuthForgotPasswordRoute;
  '/reset-password': typeof AuthResetPasswordRoute;
  '/signin': typeof AuthSigninRoute;
  '/signup': typeof AuthSignupRoute;
  '/verify': typeof AuthVerifyRoute;
  '/admin': typeof ProtectedAdminRouteWithChildren;
  '/verify-email-change/$emailToken': typeof VerifyEmailChangeEmailTokenRoute;
  '/account': typeof ProtectedAccountAccountRoute;
  '/billing': typeof ProtectedAccountBillingRoute;
  '/notifications': typeof ProtectedAccountNotificationsRoute;
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute;
  '/ws/$workspaceId': typeof ProtectedWsWorkspaceIdRouteWithChildren;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/test/emails': typeof ApiTestEmailsRoute;
  '/ws': typeof ProtectedWsIndexRoute;
  '/admin/user/$userId': typeof ProtectedAdminUserUserIdRoute;
  '/ws/$workspaceId/billing': typeof ProtectedWsWorkspaceIdBillingRoute;
  '/ws/$workspaceId/members': typeof ProtectedWsWorkspaceIdMembersRoute;
  '/ws/$workspaceId/overview': typeof ProtectedWsWorkspaceIdOverviewRoute;
  '/ws/$workspaceId/projects': typeof ProtectedWsWorkspaceIdProjectsRoute;
  '/ws/$workspaceId/settings': typeof ProtectedWsWorkspaceIdSettingsRoute;
  '/admin/user': typeof ProtectedAdminUserIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_auth': typeof AuthRouteWithChildren;
  '/_protected': typeof ProtectedRouteWithChildren;
  '/accept-invite': typeof AcceptInviteRoute;
  '/health': typeof HealthRoute;
  '/ping': typeof PingRoute;
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute;
  '/_auth/reset-password': typeof AuthResetPasswordRoute;
  '/_auth/signin': typeof AuthSigninRoute;
  '/_auth/signup': typeof AuthSignupRoute;
  '/_auth/verify': typeof AuthVerifyRoute;
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren;
  '/_protected/ws': typeof ProtectedWsRouteWithChildren;
  '/verify-email-change/$emailToken': typeof VerifyEmailChangeEmailTokenRoute;
  '/_protected/_account/account': typeof ProtectedAccountAccountRoute;
  '/_protected/_account/billing': typeof ProtectedAccountBillingRoute;
  '/_protected/_account/notifications': typeof ProtectedAccountNotificationsRoute;
  '/_protected/admin/dashboard': typeof ProtectedAdminDashboardRoute;
  '/_protected/admin/user': typeof ProtectedAdminUserRouteWithChildren;
  '/_protected/ws/$workspaceId': typeof ProtectedWsWorkspaceIdRouteWithChildren;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/test/emails': typeof ApiTestEmailsRoute;
  '/_protected/ws/': typeof ProtectedWsIndexRoute;
  '/_protected/admin/user/$userId': typeof ProtectedAdminUserUserIdRoute;
  '/_protected/ws/$workspaceId/billing': typeof ProtectedWsWorkspaceIdBillingRoute;
  '/_protected/ws/$workspaceId/members': typeof ProtectedWsWorkspaceIdMembersRoute;
  '/_protected/ws/$workspaceId/overview': typeof ProtectedWsWorkspaceIdOverviewRoute;
  '/_protected/ws/$workspaceId/projects': typeof ProtectedWsWorkspaceIdProjectsRoute;
  '/_protected/ws/$workspaceId/settings': typeof ProtectedWsWorkspaceIdSettingsRoute;
  '/_protected/admin/user/': typeof ProtectedAdminUserIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/health'
    | '/ping'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/admin'
    | '/ws'
    | '/verify-email-change/$emailToken'
    | '/account'
    | '/billing'
    | '/notifications'
    | '/admin/dashboard'
    | '/admin/user'
    | '/ws/$workspaceId'
    | '/api/auth/$'
    | '/api/test/emails'
    | '/ws/'
    | '/admin/user/$userId'
    | '/ws/$workspaceId/billing'
    | '/ws/$workspaceId/members'
    | '/ws/$workspaceId/overview'
    | '/ws/$workspaceId/projects'
    | '/ws/$workspaceId/settings'
    | '/admin/user/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/accept-invite'
    | '/health'
    | '/ping'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/admin'
    | '/verify-email-change/$emailToken'
    | '/account'
    | '/billing'
    | '/notifications'
    | '/admin/dashboard'
    | '/ws/$workspaceId'
    | '/api/auth/$'
    | '/api/test/emails'
    | '/ws'
    | '/admin/user/$userId'
    | '/ws/$workspaceId/billing'
    | '/ws/$workspaceId/members'
    | '/ws/$workspaceId/overview'
    | '/ws/$workspaceId/projects'
    | '/ws/$workspaceId/settings'
    | '/admin/user';
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/accept-invite'
    | '/health'
    | '/ping'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_auth/verify'
    | '/_protected/admin'
    | '/_protected/ws'
    | '/verify-email-change/$emailToken'
    | '/_protected/_account/account'
    | '/_protected/_account/billing'
    | '/_protected/_account/notifications'
    | '/_protected/admin/dashboard'
    | '/_protected/admin/user'
    | '/_protected/ws/$workspaceId'
    | '/api/auth/$'
    | '/api/test/emails'
    | '/_protected/ws/'
    | '/_protected/admin/user/$userId'
    | '/_protected/ws/$workspaceId/billing'
    | '/_protected/ws/$workspaceId/members'
    | '/_protected/ws/$workspaceId/overview'
    | '/_protected/ws/$workspaceId/projects'
    | '/_protected/ws/$workspaceId/settings'
    | '/_protected/admin/user/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  ProtectedRoute: typeof ProtectedRouteWithChildren;
  AcceptInviteRoute: typeof AcceptInviteRoute;
  HealthRoute: typeof HealthRoute;
  PingRoute: typeof PingRoute;
  VerifyEmailChangeEmailTokenRoute: typeof VerifyEmailChangeEmailTokenRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiTestEmailsRoute: typeof ApiTestEmailsRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ping': {
      id: '/ping';
      path: '/ping';
      fullPath: '/ping';
      preLoaderRoute: typeof PingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/health': {
      id: '/health';
      path: '/health';
      fullPath: '/health';
      preLoaderRoute: typeof HealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/accept-invite': {
      id: '/accept-invite';
      path: '/accept-invite';
      fullPath: '/accept-invite';
      preLoaderRoute: typeof AcceptInviteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected': {
      id: '/_protected';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/verify-email-change/$emailToken': {
      id: '/verify-email-change/$emailToken';
      path: '/verify-email-change/$emailToken';
      fullPath: '/verify-email-change/$emailToken';
      preLoaderRoute: typeof VerifyEmailChangeEmailTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected/ws': {
      id: '/_protected/ws';
      path: '/ws';
      fullPath: '/ws';
      preLoaderRoute: typeof ProtectedWsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/admin': {
      id: '/_protected/admin';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof ProtectedAdminRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_auth/verify': {
      id: '/_auth/verify';
      path: '/verify';
      fullPath: '/verify';
      preLoaderRoute: typeof AuthVerifyRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/signup': {
      id: '/_auth/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof AuthSignupRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/signin': {
      id: '/_auth/signin';
      path: '/signin';
      fullPath: '/signin';
      preLoaderRoute: typeof AuthSigninRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/reset-password': {
      id: '/_auth/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof AuthResetPasswordRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_protected/ws/': {
      id: '/_protected/ws/';
      path: '/';
      fullPath: '/ws/';
      preLoaderRoute: typeof ProtectedWsIndexRouteImport;
      parentRoute: typeof ProtectedWsRoute;
    };
    '/api/test/emails': {
      id: '/api/test/emails';
      path: '/api/test/emails';
      fullPath: '/api/test/emails';
      preLoaderRoute: typeof ApiTestEmailsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/auth/$': {
      id: '/api/auth/$';
      path: '/api/auth/$';
      fullPath: '/api/auth/$';
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected/ws/$workspaceId': {
      id: '/_protected/ws/$workspaceId';
      path: '/$workspaceId';
      fullPath: '/ws/$workspaceId';
      preLoaderRoute: typeof ProtectedWsWorkspaceIdRouteImport;
      parentRoute: typeof ProtectedWsRoute;
    };
    '/_protected/admin/user': {
      id: '/_protected/admin/user';
      path: '/user';
      fullPath: '/admin/user';
      preLoaderRoute: typeof ProtectedAdminUserRouteImport;
      parentRoute: typeof ProtectedAdminRoute;
    };
    '/_protected/admin/dashboard': {
      id: '/_protected/admin/dashboard';
      path: '/dashboard';
      fullPath: '/admin/dashboard';
      preLoaderRoute: typeof ProtectedAdminDashboardRouteImport;
      parentRoute: typeof ProtectedAdminRoute;
    };
    '/_protected/_account/notifications': {
      id: '/_protected/_account/notifications';
      path: '/notifications';
      fullPath: '/notifications';
      preLoaderRoute: typeof ProtectedAccountNotificationsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/_account/billing': {
      id: '/_protected/_account/billing';
      path: '/billing';
      fullPath: '/billing';
      preLoaderRoute: typeof ProtectedAccountBillingRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/_account/account': {
      id: '/_protected/_account/account';
      path: '/account';
      fullPath: '/account';
      preLoaderRoute: typeof ProtectedAccountAccountRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/admin/user/': {
      id: '/_protected/admin/user/';
      path: '/';
      fullPath: '/admin/user/';
      preLoaderRoute: typeof ProtectedAdminUserIndexRouteImport;
      parentRoute: typeof ProtectedAdminUserRoute;
    };
    '/_protected/ws/$workspaceId/settings': {
      id: '/_protected/ws/$workspaceId/settings';
      path: '/settings';
      fullPath: '/ws/$workspaceId/settings';
      preLoaderRoute: typeof ProtectedWsWorkspaceIdSettingsRouteImport;
      parentRoute: typeof ProtectedWsWorkspaceIdRoute;
    };
    '/_protected/ws/$workspaceId/projects': {
      id: '/_protected/ws/$workspaceId/projects';
      path: '/projects';
      fullPath: '/ws/$workspaceId/projects';
      preLoaderRoute: typeof ProtectedWsWorkspaceIdProjectsRouteImport;
      parentRoute: typeof ProtectedWsWorkspaceIdRoute;
    };
    '/_protected/ws/$workspaceId/overview': {
      id: '/_protected/ws/$workspaceId/overview';
      path: '/overview';
      fullPath: '/ws/$workspaceId/overview';
      preLoaderRoute: typeof ProtectedWsWorkspaceIdOverviewRouteImport;
      parentRoute: typeof ProtectedWsWorkspaceIdRoute;
    };
    '/_protected/ws/$workspaceId/members': {
      id: '/_protected/ws/$workspaceId/members';
      path: '/members';
      fullPath: '/ws/$workspaceId/members';
      preLoaderRoute: typeof ProtectedWsWorkspaceIdMembersRouteImport;
      parentRoute: typeof ProtectedWsWorkspaceIdRoute;
    };
    '/_protected/ws/$workspaceId/billing': {
      id: '/_protected/ws/$workspaceId/billing';
      path: '/billing';
      fullPath: '/ws/$workspaceId/billing';
      preLoaderRoute: typeof ProtectedWsWorkspaceIdBillingRouteImport;
      parentRoute: typeof ProtectedWsWorkspaceIdRoute;
    };
    '/_protected/admin/user/$userId': {
      id: '/_protected/admin/user/$userId';
      path: '/$userId';
      fullPath: '/admin/user/$userId';
      preLoaderRoute: typeof ProtectedAdminUserUserIdRouteImport;
      parentRoute: typeof ProtectedAdminUserRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  AuthSigninRoute: typeof AuthSigninRoute;
  AuthSignupRoute: typeof AuthSignupRoute;
  AuthVerifyRoute: typeof AuthVerifyRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface ProtectedAdminUserRouteChildren {
  ProtectedAdminUserUserIdRoute: typeof ProtectedAdminUserUserIdRoute;
  ProtectedAdminUserIndexRoute: typeof ProtectedAdminUserIndexRoute;
}

const ProtectedAdminUserRouteChildren: ProtectedAdminUserRouteChildren = {
  ProtectedAdminUserUserIdRoute: ProtectedAdminUserUserIdRoute,
  ProtectedAdminUserIndexRoute: ProtectedAdminUserIndexRoute,
};

const ProtectedAdminUserRouteWithChildren =
  ProtectedAdminUserRoute._addFileChildren(ProtectedAdminUserRouteChildren);

interface ProtectedAdminRouteChildren {
  ProtectedAdminDashboardRoute: typeof ProtectedAdminDashboardRoute;
  ProtectedAdminUserRoute: typeof ProtectedAdminUserRouteWithChildren;
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminDashboardRoute: ProtectedAdminDashboardRoute,
  ProtectedAdminUserRoute: ProtectedAdminUserRouteWithChildren,
};

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
);

interface ProtectedWsWorkspaceIdRouteChildren {
  ProtectedWsWorkspaceIdBillingRoute: typeof ProtectedWsWorkspaceIdBillingRoute;
  ProtectedWsWorkspaceIdMembersRoute: typeof ProtectedWsWorkspaceIdMembersRoute;
  ProtectedWsWorkspaceIdOverviewRoute: typeof ProtectedWsWorkspaceIdOverviewRoute;
  ProtectedWsWorkspaceIdProjectsRoute: typeof ProtectedWsWorkspaceIdProjectsRoute;
  ProtectedWsWorkspaceIdSettingsRoute: typeof ProtectedWsWorkspaceIdSettingsRoute;
}

const ProtectedWsWorkspaceIdRouteChildren: ProtectedWsWorkspaceIdRouteChildren =
  {
    ProtectedWsWorkspaceIdBillingRoute: ProtectedWsWorkspaceIdBillingRoute,
    ProtectedWsWorkspaceIdMembersRoute: ProtectedWsWorkspaceIdMembersRoute,
    ProtectedWsWorkspaceIdOverviewRoute: ProtectedWsWorkspaceIdOverviewRoute,
    ProtectedWsWorkspaceIdProjectsRoute: ProtectedWsWorkspaceIdProjectsRoute,
    ProtectedWsWorkspaceIdSettingsRoute: ProtectedWsWorkspaceIdSettingsRoute,
  };

const ProtectedWsWorkspaceIdRouteWithChildren =
  ProtectedWsWorkspaceIdRoute._addFileChildren(
    ProtectedWsWorkspaceIdRouteChildren,
  );

interface ProtectedWsRouteChildren {
  ProtectedWsWorkspaceIdRoute: typeof ProtectedWsWorkspaceIdRouteWithChildren;
  ProtectedWsIndexRoute: typeof ProtectedWsIndexRoute;
}

const ProtectedWsRouteChildren: ProtectedWsRouteChildren = {
  ProtectedWsWorkspaceIdRoute: ProtectedWsWorkspaceIdRouteWithChildren,
  ProtectedWsIndexRoute: ProtectedWsIndexRoute,
};

const ProtectedWsRouteWithChildren = ProtectedWsRoute._addFileChildren(
  ProtectedWsRouteChildren,
);

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren;
  ProtectedWsRoute: typeof ProtectedWsRouteWithChildren;
  ProtectedAccountAccountRoute: typeof ProtectedAccountAccountRoute;
  ProtectedAccountBillingRoute: typeof ProtectedAccountBillingRoute;
  ProtectedAccountNotificationsRoute: typeof ProtectedAccountNotificationsRoute;
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedWsRoute: ProtectedWsRouteWithChildren,
  ProtectedAccountAccountRoute: ProtectedAccountAccountRoute,
  ProtectedAccountBillingRoute: ProtectedAccountBillingRoute,
  ProtectedAccountNotificationsRoute: ProtectedAccountNotificationsRoute,
};

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  HealthRoute: HealthRoute,
  PingRoute: PingRoute,
  VerifyEmailChangeEmailTokenRoute: VerifyEmailChangeEmailTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTestEmailsRoute: ApiTestEmailsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
