import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  globalSetup: './test/e2e/global-setup.ts',
  testDir: './test/e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [['html', { open: 'never' }]],
  use: {
    baseURL: 'http://localhost:3001',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  webServer: [
    {
      // Serve the prebuilt E2E bundle generated by `build:e2e`.
      command: 'node --env-file=.env .output/server/index.mjs',
      url: 'http://localhost:3001',
      reuseExistingServer: true,
      env: {
        PORT: '3001',
      },
      stderr: 'pipe',
    },
  ],
});
