/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PingRouteImport } from './routes/ping';
import { Route as HealthRouteImport } from './routes/health';
import { Route as ProtectedRouteImport } from './routes/_protected';
import { Route as AuthRouteImport } from './routes/_auth';
import { Route as IndexRouteImport } from './routes/index';
import { Route as VerifyEmailChangeEmailRouteImport } from './routes/verify-email-change.$email';
import { Route as ProtectedTeamRouteImport } from './routes/_protected/team';
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings';
import { Route as ProtectedProjectsRouteImport } from './routes/_protected/projects';
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard';
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin';
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify';
import { Route as AuthSignupRouteImport } from './routes/_auth/signup';
import { Route as AuthSigninRouteImport } from './routes/_auth/signin';
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password';
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password';
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$';
import { Route as ProtectedAdminUserRouteImport } from './routes/_protected/admin/user';
import { Route as ProtectedAdminDashboardRouteImport } from './routes/_protected/admin/dashboard';
import { Route as ProtectedAccountNotificationsRouteImport } from './routes/_protected/_account/notifications';
import { Route as ProtectedAccountBillingRouteImport } from './routes/_protected/_account/billing';
import { Route as ProtectedAccountAccountRouteImport } from './routes/_protected/_account/account';
import { Route as ProtectedAdminUserIndexRouteImport } from './routes/_protected/admin/user/index';
import { Route as ProtectedAdminUserUserIdRouteImport } from './routes/_protected/admin/user/$userId';

const PingRoute = PingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => rootRouteImport,
} as any);
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const VerifyEmailChangeEmailRoute = VerifyEmailChangeEmailRouteImport.update({
  id: '/verify-email-change/$email',
  path: '/verify-email-change/$email',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedTeamRoute = ProtectedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedProjectsRoute = ProtectedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any);
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any);
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any);
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedAdminUserRoute = ProtectedAdminUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => ProtectedAdminRoute,
} as any);
const ProtectedAdminDashboardRoute = ProtectedAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedAdminRoute,
} as any);
const ProtectedAccountNotificationsRoute =
  ProtectedAccountNotificationsRouteImport.update({
    id: '/_account/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedRoute,
  } as any);
const ProtectedAccountBillingRoute = ProtectedAccountBillingRouteImport.update({
  id: '/_account/billing',
  path: '/billing',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedAccountAccountRoute = ProtectedAccountAccountRouteImport.update({
  id: '/_account/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedAdminUserIndexRoute = ProtectedAdminUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminUserRoute,
} as any);
const ProtectedAdminUserUserIdRoute =
  ProtectedAdminUserUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => ProtectedAdminUserRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/health': typeof HealthRoute;
  '/ping': typeof PingRoute;
  '/forgot-password': typeof AuthForgotPasswordRoute;
  '/reset-password': typeof AuthResetPasswordRoute;
  '/signin': typeof AuthSigninRoute;
  '/signup': typeof AuthSignupRoute;
  '/verify': typeof AuthVerifyRoute;
  '/admin': typeof ProtectedAdminRouteWithChildren;
  '/dashboard': typeof ProtectedDashboardRoute;
  '/projects': typeof ProtectedProjectsRoute;
  '/settings': typeof ProtectedSettingsRoute;
  '/team': typeof ProtectedTeamRoute;
  '/verify-email-change/$email': typeof VerifyEmailChangeEmailRoute;
  '/account': typeof ProtectedAccountAccountRoute;
  '/billing': typeof ProtectedAccountBillingRoute;
  '/notifications': typeof ProtectedAccountNotificationsRoute;
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute;
  '/admin/user': typeof ProtectedAdminUserRouteWithChildren;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/admin/user/$userId': typeof ProtectedAdminUserUserIdRoute;
  '/admin/user/': typeof ProtectedAdminUserIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/health': typeof HealthRoute;
  '/ping': typeof PingRoute;
  '/forgot-password': typeof AuthForgotPasswordRoute;
  '/reset-password': typeof AuthResetPasswordRoute;
  '/signin': typeof AuthSigninRoute;
  '/signup': typeof AuthSignupRoute;
  '/verify': typeof AuthVerifyRoute;
  '/admin': typeof ProtectedAdminRouteWithChildren;
  '/dashboard': typeof ProtectedDashboardRoute;
  '/projects': typeof ProtectedProjectsRoute;
  '/settings': typeof ProtectedSettingsRoute;
  '/team': typeof ProtectedTeamRoute;
  '/verify-email-change/$email': typeof VerifyEmailChangeEmailRoute;
  '/account': typeof ProtectedAccountAccountRoute;
  '/billing': typeof ProtectedAccountBillingRoute;
  '/notifications': typeof ProtectedAccountNotificationsRoute;
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/admin/user/$userId': typeof ProtectedAdminUserUserIdRoute;
  '/admin/user': typeof ProtectedAdminUserIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_auth': typeof AuthRouteWithChildren;
  '/_protected': typeof ProtectedRouteWithChildren;
  '/health': typeof HealthRoute;
  '/ping': typeof PingRoute;
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute;
  '/_auth/reset-password': typeof AuthResetPasswordRoute;
  '/_auth/signin': typeof AuthSigninRoute;
  '/_auth/signup': typeof AuthSignupRoute;
  '/_auth/verify': typeof AuthVerifyRoute;
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren;
  '/_protected/dashboard': typeof ProtectedDashboardRoute;
  '/_protected/projects': typeof ProtectedProjectsRoute;
  '/_protected/settings': typeof ProtectedSettingsRoute;
  '/_protected/team': typeof ProtectedTeamRoute;
  '/verify-email-change/$email': typeof VerifyEmailChangeEmailRoute;
  '/_protected/_account/account': typeof ProtectedAccountAccountRoute;
  '/_protected/_account/billing': typeof ProtectedAccountBillingRoute;
  '/_protected/_account/notifications': typeof ProtectedAccountNotificationsRoute;
  '/_protected/admin/dashboard': typeof ProtectedAdminDashboardRoute;
  '/_protected/admin/user': typeof ProtectedAdminUserRouteWithChildren;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/_protected/admin/user/$userId': typeof ProtectedAdminUserUserIdRoute;
  '/_protected/admin/user/': typeof ProtectedAdminUserIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/health'
    | '/ping'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/admin'
    | '/dashboard'
    | '/projects'
    | '/settings'
    | '/team'
    | '/verify-email-change/$email'
    | '/account'
    | '/billing'
    | '/notifications'
    | '/admin/dashboard'
    | '/admin/user'
    | '/api/auth/$'
    | '/admin/user/$userId'
    | '/admin/user/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/health'
    | '/ping'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/admin'
    | '/dashboard'
    | '/projects'
    | '/settings'
    | '/team'
    | '/verify-email-change/$email'
    | '/account'
    | '/billing'
    | '/notifications'
    | '/admin/dashboard'
    | '/api/auth/$'
    | '/admin/user/$userId'
    | '/admin/user';
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/health'
    | '/ping'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_auth/verify'
    | '/_protected/admin'
    | '/_protected/dashboard'
    | '/_protected/projects'
    | '/_protected/settings'
    | '/_protected/team'
    | '/verify-email-change/$email'
    | '/_protected/_account/account'
    | '/_protected/_account/billing'
    | '/_protected/_account/notifications'
    | '/_protected/admin/dashboard'
    | '/_protected/admin/user'
    | '/api/auth/$'
    | '/_protected/admin/user/$userId'
    | '/_protected/admin/user/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  ProtectedRoute: typeof ProtectedRouteWithChildren;
  HealthRoute: typeof HealthRoute;
  PingRoute: typeof PingRoute;
  VerifyEmailChangeEmailRoute: typeof VerifyEmailChangeEmailRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ping': {
      id: '/ping';
      path: '/ping';
      fullPath: '/ping';
      preLoaderRoute: typeof PingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/health': {
      id: '/health';
      path: '/health';
      fullPath: '/health';
      preLoaderRoute: typeof HealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected': {
      id: '/_protected';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/verify-email-change/$email': {
      id: '/verify-email-change/$email';
      path: '/verify-email-change/$email';
      fullPath: '/verify-email-change/$email';
      preLoaderRoute: typeof VerifyEmailChangeEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected/team': {
      id: '/_protected/team';
      path: '/team';
      fullPath: '/team';
      preLoaderRoute: typeof ProtectedTeamRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/settings': {
      id: '/_protected/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof ProtectedSettingsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/projects': {
      id: '/_protected/projects';
      path: '/projects';
      fullPath: '/projects';
      preLoaderRoute: typeof ProtectedProjectsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/dashboard': {
      id: '/_protected/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof ProtectedDashboardRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/admin': {
      id: '/_protected/admin';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof ProtectedAdminRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_auth/verify': {
      id: '/_auth/verify';
      path: '/verify';
      fullPath: '/verify';
      preLoaderRoute: typeof AuthVerifyRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/signup': {
      id: '/_auth/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof AuthSignupRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/signin': {
      id: '/_auth/signin';
      path: '/signin';
      fullPath: '/signin';
      preLoaderRoute: typeof AuthSigninRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/reset-password': {
      id: '/_auth/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof AuthResetPasswordRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/api/auth/$': {
      id: '/api/auth/$';
      path: '/api/auth/$';
      fullPath: '/api/auth/$';
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected/admin/user': {
      id: '/_protected/admin/user';
      path: '/user';
      fullPath: '/admin/user';
      preLoaderRoute: typeof ProtectedAdminUserRouteImport;
      parentRoute: typeof ProtectedAdminRoute;
    };
    '/_protected/admin/dashboard': {
      id: '/_protected/admin/dashboard';
      path: '/dashboard';
      fullPath: '/admin/dashboard';
      preLoaderRoute: typeof ProtectedAdminDashboardRouteImport;
      parentRoute: typeof ProtectedAdminRoute;
    };
    '/_protected/_account/notifications': {
      id: '/_protected/_account/notifications';
      path: '/notifications';
      fullPath: '/notifications';
      preLoaderRoute: typeof ProtectedAccountNotificationsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/_account/billing': {
      id: '/_protected/_account/billing';
      path: '/billing';
      fullPath: '/billing';
      preLoaderRoute: typeof ProtectedAccountBillingRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/_account/account': {
      id: '/_protected/_account/account';
      path: '/account';
      fullPath: '/account';
      preLoaderRoute: typeof ProtectedAccountAccountRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/admin/user/': {
      id: '/_protected/admin/user/';
      path: '/';
      fullPath: '/admin/user/';
      preLoaderRoute: typeof ProtectedAdminUserIndexRouteImport;
      parentRoute: typeof ProtectedAdminUserRoute;
    };
    '/_protected/admin/user/$userId': {
      id: '/_protected/admin/user/$userId';
      path: '/$userId';
      fullPath: '/admin/user/$userId';
      preLoaderRoute: typeof ProtectedAdminUserUserIdRouteImport;
      parentRoute: typeof ProtectedAdminUserRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  AuthSigninRoute: typeof AuthSigninRoute;
  AuthSignupRoute: typeof AuthSignupRoute;
  AuthVerifyRoute: typeof AuthVerifyRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface ProtectedAdminUserRouteChildren {
  ProtectedAdminUserUserIdRoute: typeof ProtectedAdminUserUserIdRoute;
  ProtectedAdminUserIndexRoute: typeof ProtectedAdminUserIndexRoute;
}

const ProtectedAdminUserRouteChildren: ProtectedAdminUserRouteChildren = {
  ProtectedAdminUserUserIdRoute: ProtectedAdminUserUserIdRoute,
  ProtectedAdminUserIndexRoute: ProtectedAdminUserIndexRoute,
};

const ProtectedAdminUserRouteWithChildren =
  ProtectedAdminUserRoute._addFileChildren(ProtectedAdminUserRouteChildren);

interface ProtectedAdminRouteChildren {
  ProtectedAdminDashboardRoute: typeof ProtectedAdminDashboardRoute;
  ProtectedAdminUserRoute: typeof ProtectedAdminUserRouteWithChildren;
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminDashboardRoute: ProtectedAdminDashboardRoute,
  ProtectedAdminUserRoute: ProtectedAdminUserRouteWithChildren,
};

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
);

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren;
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute;
  ProtectedProjectsRoute: typeof ProtectedProjectsRoute;
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute;
  ProtectedTeamRoute: typeof ProtectedTeamRoute;
  ProtectedAccountAccountRoute: typeof ProtectedAccountAccountRoute;
  ProtectedAccountBillingRoute: typeof ProtectedAccountBillingRoute;
  ProtectedAccountNotificationsRoute: typeof ProtectedAccountNotificationsRoute;
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedProjectsRoute: ProtectedProjectsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedTeamRoute: ProtectedTeamRoute,
  ProtectedAccountAccountRoute: ProtectedAccountAccountRoute,
  ProtectedAccountBillingRoute: ProtectedAccountBillingRoute,
  ProtectedAccountNotificationsRoute: ProtectedAccountNotificationsRoute,
};

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  HealthRoute: HealthRoute,
  PingRoute: PingRoute,
  VerifyEmailChangeEmailRoute: VerifyEmailChangeEmailRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
